### PR TITLE
More DRY code thanks to using inheritance + Spinners, Badges, Alerts.

### PR DESCRIPTION
**Pull request by laundmo**
When adding spinners to this, i noticed how much more DRY the code could be.

As a result, this is one big PR with both those changes, Spinners and more DRY code, and also Badges and Alerts thrown in for good measure.

AFAIK the only downside of the factory pattern is that `type(GrowDangerSpinner)` will show `Spinner` (and type checkers will do the same)

### CODE REVIEW

**Comment by fscherf** [comment]
Hi @laundmo,

i like the changes and i wan't that functionality, but i don't like the approach. I don't think the added complexity is worth the usecase.

I don't expect this code to change much in the future, because bootstrap5 wont change in a major way and Lona neither (at least from a public facing API point of view), so the maintenance on this repository will presumably remain low. So there is no point in decreasing the readability to shorten up the code in my opinion.

**Comment by laundmo** [comment]
I changed it about, it's still slightly simplified because STATIC_FILES does really not need to be redefined for every single node thanks to inheritance. This also allows people to use only a Div from this library and still get the static files.

**Comment by fscherf** [comment]
Much better, thanks! I still have some nitpicks:

* Please use single quotes instead of double quotes to be consistent with the rest of the code base
* Please don't use one-line if statements
* You define ``lona_bootstrap.nodes.Div`` as a Div that contains all Bootstrap 5 related static files. This name is confusing because it is named like ``lona.html.Div`` but behaves slightly different
* Please squash your commits together

**Comment by laundmo** [comment]
> Please use single quotes instead of double quotes to be consistent with the rest of the code base

sorry, i use the black formatter, and thats what it uses (currently theres no info what formatter should be used, i think i'll open a issue on the main repo to discuss adding pre-commit for the various tools used)

also, test_script.py used double quotes for multiline strings and single quotes for normal strings?

> Please don't use one-line if statements

i can remove it, but i have to ask why?

> You define lona_bootstrap.nodes.Div as a Div that contains all Bootstrap 5 related static files. This name is confusing because it is named like lona.html.Div but behaves slightly different

Do you think i should change the name to something like BootstrapDiv?

> Please squash your commits together

can do

**Comment by fscherf** [comment]
@laundmo,

> > Please don't use one-line if statements
> 
> i can remove it, but i have to ask why?

I generally dislike one-line statements. The benefit is very low, but they make the code less readable, especially for beginners.

Thanks for contributing! :)

**Pull request merged**
